services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
   image: postgres:alpine
   ports:
      - "5432:5432"
  vote:
    build: ./vote
    ports:
      - "80:80"
  result:
    build: ./result
    ports:
      - "81:80"
  worker:
    build: ./worker
  seed:
    build: ./seed-data